version: '2.1'

services:
  order-app:
    build:
      context: ./order-app
      dockerfile: Dockerfile
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra-order-db
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_CASSANDRA_PORT=9042
    depends_on:
      cassandra-order-db:
        condition: service_healthy
    networks:
      - dc3hub
  cassandra-order-db:
    image: cassandra:latest
    container_name: cassandra-db
    environment:
      - CASSANDRA_DC=datacenter1
    healthcheck:
      test: [ "CMD-SHELL", "[ $$(nodetool statusgossip) = running ]" ]
      interval: 120s
      timeout: 15s
      retries: 3
    ports:
      - 9042:9042
    networks:
      - dc3hub

networks:
  dc3hub:
    driver: host
